### ISSUE TITLE
Matlab update

### ISSUE THREAD

**Issue by athenaakrami** [LIMLabSWC/ratter#2]
Brodylab has updated to Matlab2019b, Marino has updated to Matlab2022a. 

From Chuck:
"As for the update you may still see a bunch of errors going to 2019b. At the time when we did that update it was early 2020 so that was the latest version.  I believe the errors you'll get are from the functions gca and gcf. THe old matlabs returned a number that you could pass as a handle to work with that particular figure or axes. Newer matlabs return an object with fields.  If you pass the output through the double function you get the old output. So essentially anywhere you see gca replace it with double(gca) and the same with gcf replace it with double(gcf)"

Marino has had the same issue/fix. 

Brodylab is mainly running Windows 10, Marino is using Windows 11. 

I suggest we test a rig with latest Matlab (even 2024a), and Windows 11, applying Chuck's fix.

**Comment by viktorpm** [comment]
Windows 11 is not LTS so we are going with 10 for now.

**Comment by athenaakrami** [comment]
ok, sure that sounds good!

*----*

*ATHENA AKRAMI, Ph.D.*

Group Leader

Learning, Inference & Memory Lab,

Sainsbury Wellcome Centre

University College London
Tel: +44(0)2031088031

***@***.*** ***@***.***> | www.ucl.ac.uk/s
<http://www.ucl.ac.uk/swc>wc | www.lim.bio <http://www.lim.bio/>*

**Comment by viktorpm** [comment]
All occurrences have been replaced using [this](https://github.com/zzzprojects/findandreplace?tab=readme-ov-file) tool. See commit: `cacd8ccdb1a60fa6b7033f2dcef45d2e9bdc93f8`.  Still not fully functional
